### ISSUE TITLE
Use integers to represent taxid

### ISSUE THREAD

**Issue by apcamargo** [apcamargo/taxopy#2]
This will reduce memory usage

**Comment by Midnighter** [comment]
I understand that this is a good optimization when only working with the NCBI taxonomy but it makes taxopy less generally applicable. The GTDB, for example, uses only non-numeric taxonomic identifiers.

In my particular case, I'm merging two taxonomies and have renamed the nodes in the subtree coming from the NCBI to `NCBI:txid[N]` in order to not have nodes clash between the two.

**Comment by apcamargo** [comment]
@Midnighter can you provide more details how you're obtaining the taxids for GTDB? Officially, they don't provide a taxdump (as far as I know), but you can get an official taxdump here: https://github.com/shenwei356/gtdb-taxdump/releases/tag/v0.1.1

**Comment by Midnighter** [comment]
I was looking at the Newick trees and TSV files at https://data.gtdb.ecogenomic.org/releases/release207/207.0/ directly.

**Comment by apcamargo** [comment]
Ohh, ok. But how did you generate the taxdump that you are loading into `taxopy`? If you haven't done this yet, I recommend downloading the one I linked above as it already follow the NCBI format (which uses integers as identifiers for taxa).

**Comment by Midnighter** [comment]
Fair point. My real use case, however, as briefly outlined above, is to combine two distinct taxonomies. So I'm inserting part of the NCBI taxonomy as a branch into another taxonomy. Both use numeric node identifiers such that conflicts would surely occur. That is why I resorted to prefixing the NCBI numeric identifiers with `NCBI:txid` which means they have to be strings. I suppose, I could also add a fixed constant to all nodes of one taxonomy.

**Comment by apcamargo** [comment]
That's probably the easiest way to go
